### PR TITLE
Introduce a convenience property list initializer, to align with OktaOAuth2 flows

### PR DESCRIPTION
**Pull request by mikenachbaur-okta**
I discovered, while documenting the authentication flows, that InteractionCodeFlow didn't consume the default Okta.plist file, as in other authentication flows.

### CODE REVIEW

**Review by emmanuelogunmuyiwa-okta — APPROVED** [review]
Looks good!

**Comment by emmanuelogunmuyiwa-okta** [comment]
Since it would be consuming the default plist now, I think it might be beneficial to add a `default/shared` instance of `InteractionCodeFlow`. Any thoughts on this ?

**Comment by mikenachbaur-okta** [comment]
The flows themselves are meant to be explicitly retained. The reason is that I want to avoid overuse / abuse of singletons. The `WebAuthentication.shared` singleton is an exception, since it's a common use-case. But using the flows directly is a more advanced use-case that is reasonable to assume a developer would be able to manage their memory properly.

**Comment by mikenachbaur-okta** [comment]
I like your point about updating docs to reflect this convenience. I'll do that before merging this PR.

**Pull request merged**
